apiVersion: v1
kind: Namespace
metadata:
  name: secret-santa
  labels:
    name: secretsanta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretsanta
  labels:
    app: secretsanta
  namespace: secret-santa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretsanta
  template:
    metadata:
      labels:
        app: secretsanta
    spec:
      containers:
      - name: secretsanta
        image: secretsanta:v0.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: secretsanta
        - containerPort: 8080
          name: metrics
        securityContext:
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30

