apiVersion: v1
kind: Namespace
metadata:
  name: secret-santa
  labels:
    name: secretsanta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretsanta
  labels:
    app: secretsanta
  namespace: secret-santa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretsanta
  template:
    metadata:
      labels:
        app: secretsanta
    spec:
      containers:
      - name: secretsanta
        image: secretsanta:v0.1.0
        # in order to build on minikube with locally built image, set pull
        # policy to Never otherwise it will try to pull from a registry instead
        # of locally
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: secretsanta
        - containerPort: 8080
          name: metrics
        securityContext:
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
          # uncomment the following after creating a mail-auth secret to
          # hold username and password required to email all the participants
        # env:
        #   - name: MAIL_USERNAME
        #     valueFrom:
        #       secretKeyRef:
        #         name: mail-auth
        #         key: username
        #   - name: MAIL_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: mail-auth
        #         key: password

