apiVersion: v1
kind: Service
metadata:
  name: secretservice
  labels:
    app: secretsanta
  namespace: secret-santa
spec:
  selector:
    app: secretsanta
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
